### ISSUE TITLE
Autostart Bug

### ISSUE THREAD

**Issue by MaxVonBPA** [MaxMorgenstern/DynDNS-Updater#11]
Send from beta tester:

Hab nen Bug im DynDNS Updater.
Er läuft bei mir ja via Autostart. Nach dem Autostart fehlen ihm allerdings die Login-Daten, bzw. offensichtlich die komplette Config. Starte ich ihn dann nochmal neu, findet er seine Config plötzlich.

**Comment by MaxMorgenstern** [comment]
fixed with latest commit
